### PR TITLE
Manually copy library files to the prefix on windows

### PR DESCRIPTION
**Pull request by pepijndevos**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by pepijndevos** [comment]
@conda-forge-admin, please rerender

**Comment by pepijndevos** [comment]
Uh what do you want me to do with the build number? Seems like you did not reset it to 0 when updating the version, so I assume I should increment it?

**Comment by pepijndevos** [comment]
No worky
image

**Comment by stuarteberg** [comment]
>Uh what do you want me to do with the build number? Seems like you did not reset it to 0 when updating the version, so I assume I should increment it?

Yeah, I tried to, but then screwed it up when fooling around with git rebases.  :-/

I think your only option is to increment it.  Don't worry, the shame is mine.

**Comment by stuarteberg** [comment]
>No worky

I'm pretty sure you need to rerender the feedstock before that will work.  So here goes:

@conda-forge-admin please rerender

**Comment by stuarteberg** [comment]
Should we be trying to (mostly) retain the logic in `visualc/make-install-vngspice.bat`?  That script copies the `.cm` files too.

My original recipe uses that script, but patches it slightly to make the following changes:

- Change destination to `%PREFIX%` instead of `c:\Spice`
- Don't hard code `ngspice.exe`, allow caller to pass either `ngspice.exe` or `ngspice.dll`

Here's what the patched version looks like.  Again, I don't actually know much about `ngspice` or Windows, so I'm blundering around in the dark here.

<details>

<summary>Contents of visualc/make-install-vngspice.bat after patch</summary>

```bat
@echo on

REM copy ngspice.exe or ngspice.dll, codemodels *.cm to C:\Spice or Spice64
REM arguments to make-install-vngspiced:
REM %1: path to ngspice.exe or ngspice.dll, %2, %3: fftw or 64 (64 bit)

if "%2" == "64" goto b64
if "%3" == "64" goto b64

set dst=%PREFIX%
set cmsrc=.\codemodels\Win32\Release

mkdir %dst%\bin
mkdir %dst%\lib\ngspice
mkdir %dst%\share\ngspice\scripts

copy "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\redist\x86\Microsoft.VC140.OPENMP\vcomp140.dll" %dst%\bin\
copy %cmsrc%\analog.cm %dst%\lib\ngspice\analog.cm
copy %cmsrc%\digital.cm %dst%\lib\ngspice\digital.cm
copy %cmsrc%\table.cm %dst%\lib\ngspice\table.cm
copy %cmsrc%\xtraevt.cm %dst%\lib\ngspice\xtraevt.cm
copy %cmsrc%\xtradev.cm %dst%\lib\ngspice\xtradev.cm
copy %cmsrc%\spice2poly.cm %dst%\lib\ngspice\spice2poly.cm
copy .\spinit_all %dst%\share\ngspice\scripts\spinit
copy .\spinitr .\spinit

if "%2" == "fftw" goto copy2
if "%3" == "fftw" goto copy2

copy %1 %dst%\bin\
goto end

:copy2
copy %1 %dst%\bin\
copy ..\..\fftw-3.3-dll32\libfftw3-3.dll %dst%\bin\
goto end

:b64

set dst=%PREFIX%
set cmsrc=.\codemodels\x64\Release

mkdir %dst%\bin
mkdir %dst%\lib\ngspice
mkdir %dst%\share\ngspice\scripts

copy "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\redist\x64\Microsoft.VC140.OPENMP\vcomp140.dll" %dst%\bin\
copy %cmsrc%\analog64.cm %dst%\lib\ngspice\analog.cm
copy %cmsrc%\digital64.cm %dst%\lib\ngspice\digital.cm
copy %cmsrc%\table64.cm %dst%\lib\ngspice\table.cm
copy %cmsrc%\xtraevt64.cm %dst%\lib\ngspice\xtraevt.cm
copy %cmsrc%\xtradev64.cm %dst%\lib\ngspice\xtradev.cm
copy %cmsrc%\spice2poly64.cm %dst%\lib\ngspice\spice2poly.cm
copy .\spinit_all %dst%\share\ngspice\scripts\spinit
copy .\spinitr64 .\spinit

if "%2" == "fftw" goto copy2-64
if "%3" == "fftw" goto copy2-64

copy %1 %dst%\bin\
goto end

:copy2-64
copy %1 %dst%\bin\
copy ..\..\fftw-3.3-dll64\libfftw3-3.dll %dst%\bin\

:end

```

<details>

**Comment by pepijndevos** [comment]
Well that's why I'm hoping to be able to test the generated package. The readme says the sharedspice solution only builds a standalone DLL.

Either way it seems wrong that both packages provide the same files.

**Comment by stuarteberg** [comment]
Okay, I think the artifacts will be downloadable after the build completes.

**Comment by pepijndevos** [comment]
I've not yet managed to get the windows thing to work but for reference this is what it installs on linux:
```
./share
./share/ngspice
./share/ngspice/scripts
./share/ngspice/scripts/spinit
./share/ngspice/scripts/spectrum
./share/ngspice/scripts/setplot
./lib
./lib/libngspice.so.0.0.2
./lib/libngspice.la
./lib/pkgconfig
./lib/pkgconfig/ngspice.pc
./lib/libngspice.so.0
./lib/libngspice.so
./include
./include/ngspice
./include/ngspice/sharedspice.h
```

**Comment by pepijndevos** [comment]
Wait should stuff be copied into `PREFIX` or `LIBRARY_PREFIX`? Because capnproto ends up in `LIBRARY_PREFIX` but the test in the ngspice recipe test if the library exists in `PREFIX`. wth?

**Comment by pepijndevos** [comment]
I was able to link to ngspice with
```
conda create -c C:\Users\User\Downloads\conda_artifacts_20220121.3.1_win_64_\conda_artifacts_20220121.3.1_win_64_\ngspice-feedstock_conda_artifacts_20220121.3.1_win_64_ ngspice-lib capnproto
```
in the anaconda shell and then in the native VS tool shell:
```
cmake -G "Visual Studio 17 2022" -T "v141" -D CMAKE_PREFIX_PATH="C:\Users\User\.conda\envs\test-ng\Library;C:\Users\User\.conda\envs\test-ng" -D CMAKE_INSTALL_PREFIX="C:\Users\User\source\install" -DCMAKE_BUILD_TYPE=Release  ..
```

Except I made a type in the include location I will fix shortly. The main question is, which prefix should it go in? I would assume `LIBRARY_PREFIX` but this does not match what the Linux build does.

**Comment by pepijndevos** [comment]
Okay wtf, so looking at libpng as an example Unix installs into PREFIX and windows into LIBRARY_PREFIX

**Comment by pepijndevos** [comment]
Relevant data point, arch pretty much does what I'm doing: https://github.com/archlinux/svntogit-community/blob/packages/ngspice/trunk/PKGBUILD

**Comment by pepijndevos** [comment]
Working like a charm now! Will remove the artifact and then it's good to merge as far as I'm concerned.

**Comment by pepijndevos** [comment]
@conda-forge-admin please rerender

**Comment by stuarteberg** [comment]
Thanks. I’m not at my desk, but I just wanted to mention that I suppose our goal should be to replicate the structure of the pre-compiled zip files that the ngspice developers publish on their downloads page. Is that what this PR does?

**Comment by pepijndevos** [comment]
No it does not. That zip has a completely useless structure with folders for msvc and mingw builds that matches no common structure. This PR is structured so that you can link to the library by setting the correct prefix. I have confirmed I can link to it by just specifying the path to the library prefix.

**Comment by pepijndevos** [comment]
Put differently it matches what other conda libraries do on windows.

**Comment by stuarteberg** [comment]
Okay, that sounds reasonable.

**Pull request merged**
