### PR TITLE
Update recipe and correctly install shared library files

### PR DESCRIPTION
**Pull request by pepijndevos**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by pepijndevos** [comment]
@conda-forge-admin, please rerender

**Comment by pepijndevos** [comment]
OSX fails with `ld: library not found for -lomp` it seems. 

This means it's an OSX change rather than an ngspice change as this comment suggests: https://github.com/conda-forge/ngspice-feedstock/pull/23#issuecomment-758842578

**Comment by pepijndevos** [comment]
FWIW Yggdrasil also has issues with llvm and openmp: https://github.com/JuliaPackaging/Yggdrasil/pull/3271

**Comment by stuarteberg** [comment]
Great. I’ll try to have a look when I get a chance. Right now I’m just on my phone. I might not be able to sit down to inspect this until later today or tomorrow.

**Comment by stuarteberg** [comment]
BTW, would you be willing to add yourself as a maintainer?

**Comment by pepijndevos** [comment]
Given how much "fun" I'm having getting my package to build, I'd rather not at this time. But if I end up using conda in my project it seems reasonable to help maintain my direct dependencies, so feel free to ask again next time I make a PR.

I can already tell you what requires looking at: all the OpenMP stuff.

I've currently just disabled it on OSX (and Linux as collateral damage) So either we just... don't do OpenMP on OSX, add an if around it, and remove the dependency. Or we need to find how to make OSX happy.

On Windows it did this hacky thing of copying a dll straight from VS, so that might straight up not work now, and I don't know a way to test it. https://github.com/imr/ngspice/blob/1a6a9e6bb60ad8d07ecbfb3f35dea22379fb73e9/visualc/make-install-vngspice.bat#L17
This seems to go against the "Package does not vendor other packages" rule, and should probably be a proper dependency?
Right now it probably works if you install ngspice but breaks if you just install ngspice-lib which no longer does that.
Or we could just ditch OpenMP on Windows as well...

In general it would be great to actually test this package, and test it with my package. (The tests in the meta.yaml only verify that the dll exists, not that you can actually successfully link against it) But as I wrote before, I've been less than successful in building the packages locally in my Windows VM, and I am not aware of a way to work locally with the packages generate by CI.

For the ngspice package the problem seems to be that the `msbuild.exe` command inputs a very specific SDK version from 2017 that I simply don't have. The problem with my own package seems to be that there is some bug in capnproto or conda that causes it to write to my virtual CD drive and fail.

**Comment by stuarteberg** [comment]
>I am not aware of a way to work locally with the packages generate by CI.

It is possible to download the built packages as "build artifacts".  First, you have to enable build artifacts in `conda-forge.yml`, as [documented here][1].

[1]: https://conda-forge.org/docs/maintainer/conda_forge_yml.html?highlight=store_build_artifacts#azure

Then you can download them and use them.  I had to do that recently for a different feedstock.  [Here's a message][2] that explains how to download build artifacts and use them (on unix -- presumably windows is similar).

[2]: https://github.com/conda-forge/graph-tool-feedstock/pull/72#issuecomment-1005051356

**Comment by pepijndevos** [comment]
Looked around a bit: https://github.com/search?q=org%3Aconda-forge+llvm-openmp&type=code
This seems relevant: https://github.com/Quantco/tabmat/blob/main/setup.py#L53-L80
I don't see anyone manually copying the windows dll or passing `-lomp`

**Comment by pepijndevos** [comment]
It seems like the `-lomp` comes from `OPENMP_CFLAGS` which is defined by autoconf with `AC_OPENMP`. 
https://github.com/imr/ngspice/blob/e87fcbabdf65b76f7f1709a9dc0095def9f527a1/configure.ac#L1314-L1322

**Comment by stuarteberg** [comment]
@pepijndevos I patched one of the `xspice` makefiles to use better `LDFLAGS` on OSX.  With that fix, we can still build with OpenMP.

I merged the changes in #26, which also upgrades to `ngspice-36`.  That PR also includes some of the changes you added here.  (Like you, I discovered that our little test circuit doesn't seem to work.  I switched to a simpler one.)

I haven't yet changed the Windows install location.  If you'd like to open a new PR with just that change, I can take a look at some point.

**Comment by pepijndevos** [comment]
Yay! Okay this pr is superseded by #27 then

**Pull request closed without merging**
